# Sample docker-compose for openig
# Important note: The docker container that you deploy must
# be able to reach any network IPs that your OpenIG config
# might reference. This also included DNS resolution.
# This might be different than what your host (e.g. Mac OS) can reach
# This is where a Kubernetes deployment is going to make this easier
# as it can wire up DNS and service reachability
openig-nightly:
  image: forgerock/openig:nightly
  # 8080 is often used - so lets remap this to something else
  ports:
   - "5080:8080"
  # Below is an example of mounting a volume so you can do
  # Local development.
  # Note on MacOS / Docker you need to setup Docker Machine so it
  # shares and mounts your home directory onto the Docker Machine.
  # This should be done for you..
  # If your home dir is not mounted, the volumne mounts are relative to the VM - not your
  # Mac
  volumes:
    - /Users/warren/.openig:/root/openig
