#Example of how to run OpenDJ with a custom configuration
# This will mount the cts directory on the bootstrap - so we get a cts configuration
# See README.md
opendj:
  build: .
  ports:
   - "389:389"
  volumes:
    - ./cts:/opt/opendj/bootstrap
# uncomment to create a persistent directory
#    - /tmp/opendj:/opt/opendj/data
