# Sample docker-compose that will run OpenIDM and use Postgres as the repo

# The postgres image below will save the data to the host's /var/tmp/pg
# This will give you persistence across restarts
openidm-postgres:
  image: forgerock/openidm-postgres
  volumes:
    - /var/tmp/pg:/var/lib/postgresql/data/pgdata
  environment:
    PGDATA: /var/lib/postgresql/data/pgdata
    POSTGRES_PASSWORD: openidm
    POSTGRES_USER: openidm
# Run openidm - linked to postgres container
# Todo: Show an example of mounting Mac config volume for developement
# You must create a customizations dir with the repo file for postgres, etc.
openidm-nightly:
  image: forgerock/openidm
  ports:
   - "5000:8080"
  links:
   - openidm-postgres:postgres
   environment:
     OPENIDM_CUSTOM_DIR:  "FIX ME path to my customizations.."
