# Sample docker-compose that will run OpenIDM and use Postgres as the repo

# The postgres image below will save the data to the host's /var/tmp/pg
# This will give you persistence across restarts
openidm-postgres:
  image: forgerock/openidm-postgres
  volumes:
    - /var/tmp/pg:/var/lib/postgresql/data/pgdata
  environment:
    PGDATA: /var/lib/postgresql/data/pgdata
    POSTGRES_PASSWORD: openidm
    POSTGRES_USER: openidm
# Run openidm - linked to postgres container
# Shows an example of mounting local Mac config volume for developement
#
openidm-nightly:
  image: forgerock/openidm:nightly
  ports:
   - "5000:8080"
  links:
   - openidm-postgres:postgres
  volumes:
    - ~/src/k8s/stack-config:/opt/openidm/custom
  command: /opt/openidm/startup.sh -p custom/openidm
